<script setup>
import { ref, computed, watch, defineAsyncComponent, onMounted, onBeforeUnmount } from 'vue'
import { categories, allComponents, slugOf, findBySlug, docUrl } from '~/components/catalog/registry'
import { playgrounds } from '~/components/catalog/playground'

const route = useRoute()
const slug = computed(() => String(route.params.slug || ''))
const entry = computed(() => findBySlug(slug.value))

// Live demo component + its raw source (kept in sync automatically:
// the same .vue file is both rendered and displayed as code)
const demoLoaders = import.meta.glob('~/components/catalog/demos/*.vue')
const sourceLoaders = import.meta.glob('~/components/catalog/demos/*.vue', { query: '?raw', import: 'default' })
const demoKey = name => Object.keys(demoLoaders).find(k => k.endsWith(`/${name}.vue`))

const demo = computed(() => {
  const key = entry.value && demoKey(entry.value.name)
  return key ? defineAsyncComponent(demoLoaders[key]) : null
})

const source = ref('')
watch(entry, async (e) => {
  const key = e && demoKey(e.name)
  source.value = key ? await sourceLoaders[key]() : ''
}, { immediate: true })

// Extracted API docs (props / events / slots), generated by
// scripts/generate-catalog-api.mjs from primevue's index.d.ts files
const apiLoaders = import.meta.glob('~/components/catalog/api/*.json', { import: 'default' })
const { data: api } = await useAsyncData('catalog-api', async () => {
  const key = Object.keys(apiLoaders).find(k => k.endsWith(`/${slug.value}.json`))
  return key ? await apiLoaders[key]() : null
}, { watch: [slug], default: () => null })
const visibleProps = computed(() => (api.value?.props || []).filter(p => !p.deprecated))
const visibleEvents = computed(() => (api.value?.events || []).filter(e => !e.deprecated))
const visibleSlots = computed(() => (api.value?.slots || []).filter(s => !s.deprecated))

// Interactive playground: renders the bare component with live prop controls
// auto-generated from the extracted API types
const pg = computed(() => (entry.value && playgrounds[entry.value.name]) || null)
const pgComp = computed(() => (pg.value ? defineAsyncComponent(pg.value.load) : null))

const edits = ref({})
const pgModel = ref(undefined)
watch(pg, (p) => {
  edits.value = {}
  pgModel.value = p && 'model' in p ? p.model : undefined
}, { immediate: true })

const pgBindings = computed(() => {
  const b = { ...(pg.value?.seed || {}), ...edits.value }
  if (pg.value && 'model' in pg.value) {
    b.modelValue = pgModel.value
    b['onUpdate:modelValue'] = (v) => { pgModel.value = v }
  }
  return b
})

// Maps an extracted TypeScript prop type to an editable control, if possible
function controlFor(p) {
  const t = p.type.trim()
  if (t === 'boolean') return { kind: 'bool' }
  if (t === 'number') return { kind: 'number' }
  if (t === 'string' || t === 'string | number' || t === 'number | string') return { kind: 'text' }
  const hinted = t.match(/^HintedString<(.+)>$/)
  const parts = (hinted ? hinted[1] : t).split('|').map(s => s.trim())
  if (parts.length > 1 && parts.every(s => /^'[^']*'$/.test(s))) {
    return { kind: 'select', options: parts.map(s => s.slice(1, -1)), editable: !!hinted }
  }
  return null
}

const controls = computed(() => {
  if (!pg.value) return []
  return visibleProps.value
    .filter(p => p.name !== 'modelValue')
    .map(p => ({ ...p, control: controlFor(p) }))
    .filter(p => p.control)
})

const curValue = p => edits.value[p.name] ?? pg.value?.seed?.[p.name]
const boolValue = (p) => {
  const v = curValue(p)
  return v !== undefined ? !!v : p.default === 'true'
}
const setValue = (name, v) => {
  if (v === '' || v === null || v === undefined) delete edits.value[name]
  else edits.value[name] = v
}
const touched = computed(() => Object.keys(edits.value).length > 0)
const resetEdits = () => {
  edits.value = {}
  pgModel.value = pg.value && 'model' in pg.value ? pg.value.model : undefined
}

// Prev / next component navigation
const index = computed(() => allComponents.findIndex(c => slugOf(c.name) === slug.value))
const prev = computed(() => allComponents[index.value - 1])
const next = computed(() => allComponents[index.value + 1])

const query = ref('')
const filtered = computed(() => {
  const q = query.value.trim().toLowerCase()
  if (!q) return categories
  return categories
    .map(c => ({ ...c, items: c.items.filter(i => i.toLowerCase().includes(q)) }))
    .filter(c => c.items.length)
})

const showCode = ref(false)
const copied = ref(false)
const copyCode = async () => {
  await navigator.clipboard.writeText(source.value)
  copied.value = true
  setTimeout(() => { copied.value = false }, 1500)
}

const main = ref(null)
watch(slug, () => {
  showCode.value = false
  main.value?.scrollTo({ top: 0 })
})

const dark = useState('catalog-dark', () => false)
watch(dark, v => document.documentElement.classList.toggle('dark', v))
onMounted(() => document.documentElement.classList.toggle('dark', dark.value))
// The editor page styles itself for dark UI without the PrimeVue dark selector,
// so the class must not leak out of the catalog.
onBeforeUnmount(() => document.documentElement.classList.remove('dark'))
</script>

<template>
  <div class="catalog" :class="{ 'catalog-dark': dark }">
    <Toast />

    <header class="catalog-bar">
      <div class="bar-left">
        <NuxtLink to="/" class="back-link"><i class="pi pi-arrow-left" /> Editor</NuxtLink>
        <div class="bar-title">
          <span class="bar-logo">F</span>
          PrimeVue Catalog
          <span class="bar-count">{{ allComponents.length }} components</span>
        </div>
      </div>
      <div class="bar-right">
        <a class="bar-link" href="https://primevue.org" target="_blank" rel="noopener">primevue.org <i class="pi pi-external-link" /></a>
        <Button
          :icon="dark ? 'pi pi-sun' : 'pi pi-moon'" severity="secondary" text rounded
          :aria-label="dark ? 'Switch to light mode' : 'Switch to dark mode'" @click="dark = !dark"
        />
      </div>
    </header>

    <div class="catalog-body">
      <aside class="catalog-nav">
        <IconField class="nav-search">
          <InputIcon class="pi pi-search" />
          <InputText v-model="query" placeholder="Search components" fluid size="small" />
        </IconField>
        <nav>
          <div v-for="cat in filtered" :key="cat.label" class="nav-group">
            <div class="nav-cat">{{ cat.label }}</div>
            <NuxtLink
              v-for="item in cat.items" :key="item"
              :to="`/catalog/${slugOf(item)}`" class="nav-item"
              :class="{ active: slugOf(item) === slug }"
            >
              {{ item }}
            </NuxtLink>
          </div>
          <p v-if="!filtered.length" class="nav-empty">No matches for “{{ query }}”</p>
        </nav>
      </aside>

      <main ref="main" class="catalog-main">
        <template v-if="entry">
          <header class="comp-header">
            <div class="comp-heading">
              <span class="comp-cat">{{ entry.category }}</span>
              <h1 class="comp-name">{{ entry.name }}</h1>
            </div>
            <a class="comp-doclink" :href="docUrl(entry.name)" target="_blank" rel="noopener">
              <i class="pi pi-external-link" /> primevue.org/{{ slug }}
            </a>
          </header>
          <p v-if="api?.description" class="comp-desc">{{ api.description }}</p>

          <section v-if="pg" class="pg-section">
            <div class="pg-head">
              <h2>Playground</h2>
              <button v-if="touched" class="ghost-btn" @click="resetEdits">
                <i class="pi pi-refresh" /> Reset
              </button>
            </div>
            <div class="pg-grid">
              <div class="pg-stage">
                <div class="pg-stage-inner" :style="pg.stageStyle">
                  <component :is="pgComp" v-if="pg.content" v-bind="pgBindings">{{ pg.content }}</component>
                  <component :is="pgComp" v-else v-bind="pgBindings" />
                </div>
                <div v-if="'model' in pg" class="pg-model">
                  v-model: <code>{{ JSON.stringify(pgModel) }}</code>
                </div>
              </div>
              <div class="pg-controls">
                <div v-for="p in controls" :key="p.name" class="pg-row" :title="p.description">
                  <label class="pg-label">{{ p.name }}</label>
                  <div class="pg-input">
                    <ToggleSwitch
                      v-if="p.control.kind === 'bool'"
                      :model-value="boolValue(p)" @update:model-value="v => setValue(p.name, v)"
                    />
                    <InputNumber
                      v-else-if="p.control.kind === 'number'"
                      :model-value="curValue(p)" :placeholder="p.default" size="small" fluid
                      @update:model-value="v => setValue(p.name, v)"
                    />
                    <Select
                      v-else-if="p.control.kind === 'select'"
                      :model-value="curValue(p)" :options="p.control.options" :editable="p.control.editable"
                      :placeholder="p.default ?? 'default'" show-clear size="small" fluid
                      @update:model-value="v => setValue(p.name, v)"
                    />
                    <InputText
                      v-else
                      :model-value="curValue(p) ?? ''" :placeholder="p.default ?? ''" size="small" fluid
                      @update:model-value="v => setValue(p.name, v)"
                    />
                  </div>
                </div>
              </div>
            </div>
          </section>

          <h2 class="examples-title">Examples</h2>
          <section class="preview-wrap">
            <div class="preview">
              <component :is="demo" v-if="demo" />
              <p v-else class="preview-missing">No demo available for this component.</p>
            </div>
            <div class="preview-actions">
              <button class="ghost-btn" @click="showCode = !showCode">
                <i class="pi pi-code" /> {{ showCode ? 'Hide code' : 'Show code' }}
              </button>
              <button v-if="showCode" class="ghost-btn" @click="copyCode">
                <i :class="copied ? 'pi pi-check' : 'pi pi-copy'" /> {{ copied ? 'Copied' : 'Copy' }}
              </button>
            </div>
            <pre v-if="showCode" class="code-block"><code>{{ source }}</code></pre>
          </section>

          <template v-if="api">
            <section v-if="visibleProps.length" class="api-section">
              <h2>Props <span class="api-count">{{ visibleProps.length }}</span></h2>
              <p v-if="api.extends" class="api-extends">Also accepts everything from <code>{{ api.extends }}</code>.</p>
              <div class="table-scroll">
                <table class="api-table">
                  <thead>
                    <tr><th>Name</th><th>Type</th><th>Default</th><th>Description</th></tr>
                  </thead>
                  <tbody>
                    <tr v-for="p in visibleProps" :key="p.name">
                      <td class="cell-name">{{ p.name }}</td>
                      <td class="cell-type"><code>{{ p.type }}</code></td>
                      <td class="cell-default"><code v-if="p.default !== undefined">{{ p.default }}</code><span v-else>—</span></td>
                      <td class="cell-desc">{{ p.description }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>

            <section v-if="visibleEvents.length" class="api-section">
              <h2>Events <span class="api-count">{{ visibleEvents.length }}</span></h2>
              <div class="table-scroll">
                <table class="api-table">
                  <thead>
                    <tr><th>Name</th><th>Signature</th><th>Description</th></tr>
                  </thead>
                  <tbody>
                    <tr v-for="e in visibleEvents" :key="e.name">
                      <td class="cell-name">{{ e.name }}</td>
                      <td class="cell-type"><code>{{ e.type }}</code></td>
                      <td class="cell-desc">{{ e.description }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>

            <section v-if="visibleSlots.length" class="api-section">
              <h2>Slots <span class="api-count">{{ visibleSlots.length }}</span></h2>
              <div class="table-scroll">
                <table class="api-table">
                  <thead>
                    <tr><th>Name</th><th>Description</th></tr>
                  </thead>
                  <tbody>
                    <tr v-for="s in visibleSlots" :key="s.name">
                      <td class="cell-name">{{ s.name }}</td>
                      <td class="cell-desc">{{ s.description }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>
          </template>

          <nav class="pager">
            <NuxtLink v-if="prev" :to="`/catalog/${slugOf(prev.name)}`" class="pager-link">
              <i class="pi pi-arrow-left" />
              <span><small>{{ prev.category }}</small>{{ prev.name }}</span>
            </NuxtLink>
            <span v-else />
            <NuxtLink v-if="next" :to="`/catalog/${slugOf(next.name)}`" class="pager-link pager-next">
              <span><small>{{ next.category }}</small>{{ next.name }}</span>
              <i class="pi pi-arrow-right" />
            </NuxtLink>
          </nav>

          <footer class="cat-footer">
            Editor and Chart are not in the catalog — they need the extra <code>quill</code> and <code>chart.js</code> dependencies.
          </footer>
        </template>

        <div v-else class="not-found">
          <h1>Component not found</h1>
          <p>No component named “{{ slug }}” in the catalog.</p>
          <NuxtLink to="/catalog/button" class="ghost-btn">Go to Button</NuxtLink>
        </div>
      </main>
    </div>
  </div>
</template>

<style scoped>
.catalog {
  height: 100vh; width: 100vw;
  display: flex; flex-direction: column;
  background: var(--p-surface-50, #f8fafc);
  color: var(--p-text-color, #334155);
  font-family: 'Inter', system-ui, sans-serif;
  font-size: 14px;
}
.catalog-dark { background: var(--p-surface-950, #09090b); }

/* ---- top bar ---- */
.catalog-bar {
  display: flex; align-items: center; justify-content: space-between;
  height: 52px; padding: 0 16px; flex-shrink: 0;
  background: var(--p-content-background, #fff);
  border-bottom: 1px solid var(--p-content-border-color, #e2e8f0);
}
.bar-left, .bar-right { display: flex; align-items: center; gap: 14px; }
.back-link {
  display: inline-flex; align-items: center; gap: 6px;
  font-size: 13px; text-decoration: none; color: inherit; opacity: .7;
  padding: 6px 10px; border-radius: 6px;
}
.back-link:hover { opacity: 1; background: var(--p-surface-100, #f1f5f9); }
.catalog-dark .back-link:hover { background: var(--p-surface-800, #27272a); }
.bar-title { display: flex; align-items: center; gap: 8px; font-weight: 600; }
.bar-logo {
  width: 24px; height: 24px; border-radius: 6px;
  background: linear-gradient(135deg, #7c5cfc, #a78bfa);
  color: #fff; font-size: 12px; font-weight: 800;
  display: flex; align-items: center; justify-content: center;
}
.bar-count {
  font-size: 12px; font-weight: 400; opacity: .6;
  border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 999px; padding: 2px 10px;
}
.bar-link {
  font-size: 13px; text-decoration: none; color: inherit; opacity: .7;
  display: inline-flex; align-items: center; gap: 5px;
}
.bar-link:hover { opacity: 1; }
.bar-link .pi { font-size: 10px; }

.catalog-body { display: flex; flex: 1; overflow: hidden; }

/* ---- sidebar ---- */
.catalog-nav {
  width: 230px; flex-shrink: 0; overflow-y: auto;
  padding: 16px 12px 32px;
  border-right: 1px solid var(--p-content-border-color, #e2e8f0);
  background: var(--p-content-background, #fff);
}
.nav-search { margin-bottom: 14px; }
.nav-group { margin-bottom: 6px; }
.nav-cat {
  font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .06em;
  opacity: .55; padding: 12px 8px 4px;
}
.nav-item {
  display: block; padding: 5px 8px;
  font-size: 13px; color: inherit; opacity: .85; text-decoration: none;
  border-radius: 6px;
}
.nav-item:hover {
  background: var(--p-surface-100, #f1f5f9);
  color: var(--p-primary-color, #10b981); opacity: 1;
}
.catalog-dark .nav-item:hover { background: var(--p-surface-800, #27272a); }
.nav-item.active {
  background: var(--p-highlight-background, #ecfdf5);
  color: var(--p-primary-color, #10b981);
  font-weight: 600; opacity: 1;
}
.nav-empty { padding: 8px; font-size: 13px; opacity: .6; }

/* ---- main ---- */
.catalog-main { flex: 1; overflow-y: auto; padding: 28px 36px 60px; }

.comp-header {
  display: flex; align-items: flex-end; justify-content: space-between;
  gap: 16px; flex-wrap: wrap; max-width: 1080px;
}
.comp-cat {
  font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .06em;
  color: var(--p-primary-color, #10b981);
}
.comp-name { font-size: 28px; font-weight: 800; margin: 2px 0 0; }
.comp-doclink {
  display: inline-flex; align-items: center; gap: 6px;
  font-size: 13px; text-decoration: none;
  color: var(--p-primary-color, #10b981);
  border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 8px; padding: 7px 12px;
  background: var(--p-content-background, #fff);
}
.comp-doclink:hover { border-color: var(--p-primary-color, #10b981); }
.comp-desc { max-width: 1080px; margin: 10px 0 0; font-size: 15px; opacity: .8; }

/* ---- playground ---- */
.pg-section { max-width: 1080px; margin-top: 24px; }
.pg-head { display: flex; align-items: center; gap: 12px; margin-bottom: 10px; }
.pg-head h2 { font-size: 18px; font-weight: 700; margin: 0; }
.pg-grid {
  display: grid; grid-template-columns: 1fr 320px; gap: 14px;
  align-items: stretch;
}
@media (max-width: 900px) { .pg-grid { grid-template-columns: 1fr; } }
.pg-stage {
  border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 10px;
  background: var(--p-content-background, #fff);
  display: flex; flex-direction: column;
  min-height: 220px;
}
.pg-stage-inner {
  flex: 1; display: flex; align-items: center; justify-content: center;
  padding: 28px 24px; margin: 0 auto;
}
.pg-model {
  border-top: 1px dashed var(--p-content-border-color, #e2e8f0);
  padding: 8px 14px; font-size: 12px; opacity: .7;
}
.pg-model code { font-family: ui-monospace, Menlo, monospace; user-select: text; }
.pg-controls {
  border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 10px;
  background: var(--p-content-background, #fff);
  padding: 8px 14px;
  max-height: 420px; overflow-y: auto;
}
.pg-row {
  display: flex; align-items: center; justify-content: space-between; gap: 12px;
  padding: 7px 0;
  border-bottom: 1px solid var(--p-content-border-color, #e2e8f0);
}
.pg-row:last-child { border-bottom: none; }
.pg-label {
  font-size: 12.5px; font-weight: 600; flex-shrink: 0;
  font-family: ui-monospace, Menlo, monospace;
  cursor: help;
}
.pg-input { width: 150px; flex-shrink: 0; display: flex; justify-content: flex-end; }

/* ---- preview + code ---- */
.examples-title { max-width: 1080px; font-size: 18px; font-weight: 700; margin: 32px 0 0; }
.preview-wrap { max-width: 1080px; margin-top: 10px; }
.preview {
  border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 10px;
  background: var(--p-content-background, #fff);
  padding: 28px 24px;
  display: flex; flex-wrap: wrap; align-items: center; gap: 14px;
}
.preview-missing { opacity: .6; margin: 0; }
.preview-actions { display: flex; gap: 8px; margin-top: 10px; }
.ghost-btn {
  display: inline-flex; align-items: center; gap: 6px;
  font: inherit; font-size: 13px; color: inherit; opacity: .8;
  background: none; border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 6px; padding: 5px 10px; cursor: pointer; text-decoration: none;
}
.ghost-btn:hover { opacity: 1; border-color: var(--p-primary-color, #10b981); }
.code-block {
  margin: 10px 0 0; padding: 16px 18px;
  background: #16181d; color: #e2e8f0;
  border-radius: 10px; overflow-x: auto;
  font-family: ui-monospace, 'JetBrains Mono', Menlo, monospace;
  font-size: 12.5px; line-height: 1.6;
  user-select: text;
}

/* ---- API tables ---- */
.api-section { max-width: 1080px; margin-top: 36px; }
.api-section h2 {
  font-size: 18px; font-weight: 700; margin: 0 0 10px;
  display: flex; align-items: center; gap: 8px;
}
.api-count {
  font-size: 11px; font-weight: 600; opacity: .6;
  border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 999px; padding: 1px 8px;
}
.api-extends { font-size: 13px; opacity: .7; margin: 0 0 10px; }
.table-scroll {
  overflow-x: auto;
  border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 10px;
  background: var(--p-content-background, #fff);
}
.api-table { width: 100%; border-collapse: collapse; font-size: 13px; user-select: text; }
.api-table th {
  text-align: left; font-weight: 600; font-size: 12px;
  padding: 10px 14px;
  border-bottom: 1px solid var(--p-content-border-color, #e2e8f0);
  background: var(--p-surface-50, #f8fafc);
}
.catalog-dark .api-table th { background: var(--p-surface-900, #18181b); }
.api-table td {
  padding: 9px 14px; vertical-align: top;
  border-bottom: 1px solid var(--p-content-border-color, #e2e8f0);
}
.api-table tr:last-child td { border-bottom: none; }
.cell-name { font-weight: 600; white-space: nowrap; }
.cell-type code, .cell-default code, .api-extends code, .cat-footer code {
  font-family: ui-monospace, Menlo, monospace; font-size: 12px;
  background: var(--p-surface-100, #f1f5f9);
  border-radius: 4px; padding: 1px 5px;
  word-break: break-word;
}
.catalog-dark .cell-type code, .catalog-dark .cell-default code,
.catalog-dark .api-extends code, .catalog-dark .cat-footer code { background: var(--p-surface-800, #27272a); }
.cell-type { max-width: 320px; }
.cell-desc { opacity: .85; min-width: 220px; }

/* ---- pager / footer ---- */
.pager {
  max-width: 1080px; margin-top: 40px;
  display: flex; justify-content: space-between; gap: 12px;
}
.pager-link {
  display: inline-flex; align-items: center; gap: 10px;
  text-decoration: none; color: inherit;
  border: 1px solid var(--p-content-border-color, #e2e8f0);
  border-radius: 10px; padding: 10px 16px;
  background: var(--p-content-background, #fff);
}
.pager-link:hover { border-color: var(--p-primary-color, #10b981); }
.pager-link span { display: flex; flex-direction: column; font-weight: 600; }
.pager-link small { font-weight: 400; font-size: 11px; opacity: .6; }
.pager-next span { text-align: right; }
.cat-footer { max-width: 1080px; margin-top: 36px; font-size: 12px; opacity: .55; }

.not-found { padding: 60px 0; text-align: center; }
.not-found h1 { font-size: 22px; }
.not-found .ghost-btn { margin-top: 12px; display: inline-flex; }
</style>
